



CREATE DATABASE IF NOT EXISTS hot_loads_db;

USE hot_loads_db;

CREATE TABLE shipment (item_id INT AUTO_INCREMENT PRIMARY KEY, item VARCHAR(1000) NOT NULL, pickup VARCHAR(1000) NOT NULL, 
delivery VARCHAR(1000) NOT NULL, tripMiles INTEGER(6) UNSIGNED NOT NULL, 
details VARCHAR(1000) NOT NULL, pricePerMile DECIMAL(19, 4) UNSIGNED NOT NULL);